from abc import ABCMeta, abstractmethod


class AbstractProduct(object):
    """
    Common interface for products generated by the factory method. Modify it 
    in order to add your products' expected features!
    """
    
    __metaclass__ = ABCMeta

    @abstractmethod
    def feature(self):
        pass
