package tk.csparpa.gofdp.factorymethod;

/**
 * 
 * Common interface for products generated by the factory method. Modify it 
 * in order to add your products' expected features!
 * 
 */
public interface AbstractProduct {
	
	public void feature();

}
